const REGISTER_USER_LOADING="registerloading";
const REGISTER_USER_SUCCESS="registersuccess";
const REGISTER_USER_ERROR="registererror";
export {REGISTER_USER_LOADING,REGISTER_USER_SUCCESS,REGISTER_USER_ERROR}